/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrental;

import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.Vector;


/**
 *
 * @author Kavishka
 */
public class Return extends javax.swing.JFrame {

    /**
     * Creates new form Return
     */
    public Return() {
        initComponents();
        tbload();
    }
    
    public void tbload(){
        try{
            DefaultTableModel dt=(DefaultTableModel) jTable1.getModel();
            dt.setRowCount(0);
            
            Statement s=DB.mycon().createStatement();
            ResultSet rs = s.executeQuery("select * from returncar");
            
            while(rs.next()){
                Vector v=new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                
                dt.addRow(v);
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        car_id = new javax.swing.JTextField();
        fine = new javax.swing.JTextField();
        elapsed_days = new javax.swing.JTextField();
        customer_id = new javax.swing.JTextField();
        add1 = new javax.swing.JButton();
        add2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        total_amount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setText(" RETURN CAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 240, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 255));
        jLabel3.setText("Car ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 120, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 255));
        jLabel4.setText("Customer ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 130, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 255));
        jLabel5.setText("Elapsed Days");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 120, 30));

        car_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        car_id.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        car_id.setActionCommand("<Not Set>");
        car_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_idActionPerformed(evt);
            }
        });
        jPanel1.add(car_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 140, 30));

        fine.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fine.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fineMouseClicked(evt);
            }
        });
        fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fineActionPerformed(evt);
            }
        });
        jPanel1.add(fine, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 140, 30));

        elapsed_days.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        elapsed_days.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        elapsed_days.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                elapsed_daysMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                elapsed_daysMouseReleased(evt);
            }
        });
        elapsed_days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elapsed_daysActionPerformed(evt);
            }
        });
        elapsed_days.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                elapsed_daysKeyTyped(evt);
            }
        });
        jPanel1.add(elapsed_days, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 140, 30));

        customer_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customer_id.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        customer_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_idActionPerformed(evt);
            }
        });
        jPanel1.add(customer_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 140, 30));

        add1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        add1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        add1.setText("Return");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        jPanel1.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 110, 40));

        add2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        add2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        add2.setText("Clear");
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });
        jPanel1.add(add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 110, 40));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car_ID", "Customer_ID", "Elapsed_Days", "Fine", "Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 770, 150));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 255));
        jLabel7.setText("Total Payment");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 140, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 255));
        jLabel9.setText("Fine");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 100, 30));

        total_amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        total_amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_amountActionPerformed(evt);
            }
        });
        jPanel1.add(total_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 140, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\kavis\\Desktop\\javaProject\\CarRental\\src\\carrental\\imgonline-com-ua-resize-voABZ1864c6UrtS5.jpg")); // NOI18N
        jLabel6.setText("bel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void car_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_car_idActionPerformed

    private void elapsed_daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elapsed_daysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elapsed_daysActionPerformed

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
        // TODO add your handling code here:
        car_id.setText("");
        customer_id.setText("");
        elapsed_days.setText("");
        fine.setText("");
        total_amount.setText("");
    }//GEN-LAST:event_add2ActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        // TODO add your handling code here:
        String txt1 = car_id.getText();
        String txt2=customer_id.getText();
        String txt3=elapsed_days.getText();
        String txt4=fine.getText();
        String txt5=total_amount.getText();
        
        try{
            Statement s=(Statement) DB.mycon().createStatement();
            s.executeUpdate("INSERT INTO returncar VALUES ('"+txt1+"','"+txt2+"','"+txt3+"','"+txt4+"','"+txt5+"')");
            JOptionPane.showMessageDialog(rootPane, "Successfully Return!");
            
        }catch(Exception e){
            
        }
        tbload();
        
    }//GEN-LAST:event_add1ActionPerformed

    private void customer_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_idActionPerformed

    private void fineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fineActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fineActionPerformed

    private void elapsed_daysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_elapsed_daysKeyTyped
        // TODO add your handling code here:   
     
    }//GEN-LAST:event_elapsed_daysKeyTyped

    private void elapsed_daysMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elapsed_daysMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_elapsed_daysMouseReleased

    private void elapsed_daysMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elapsed_daysMouseExited
        // TODO add your handling code here:
        String Edays=elapsed_days.getText();
        int daysInt=Integer.parseInt(Edays); 
        double fineMonth=1000.00;
        double total=fineMonth*daysInt;
        String s=String.valueOf(total);
        fine.setText(s);
        
        double amount = 1500.00;
        double totalAmount=amount+total;
        String s2=String.valueOf(totalAmount);
        total_amount.setText(s2);
    }//GEN-LAST:event_elapsed_daysMouseExited

    private void fineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fineMouseClicked
        // TODO add your handling code here:
        String Edays=elapsed_days.getText();
        int daysInt=Integer.parseInt(Edays); 
        double fineMonth=1000.00;
        double total=fineMonth*daysInt;
        String s=String.valueOf(total);
        fine.setText(s);
    }//GEN-LAST:event_fineMouseClicked

    private void total_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_amountActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_total_amountActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        int r = jTable1.getSelectedRow();
        
        String ca_id=jTable1.getValueAt(r,0).toString();
        String cu_id=jTable1.getValueAt(r,1).toString();
        String eday=jTable1.getValueAt(r,2).toString();
        String f=jTable1.getValueAt(r,3).toString();
        String t_amount=jTable1.getValueAt(r,4).toString();
        
        car_id.setText(ca_id);
        customer_id.setText(cu_id);
        elapsed_days.setText(eday);
        fine.setText(f);
        total_amount.setText(t_amount);
        
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add1;
    private javax.swing.JButton add2;
    private javax.swing.JTextField car_id;
    private javax.swing.JTextField customer_id;
    private javax.swing.JTextField elapsed_days;
    private javax.swing.JTextField fine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField total_amount;
    // End of variables declaration//GEN-END:variables
}
